module.exports =  [
    "General",
    "Dress and Accessories",
    "Health",
    "Misc",
    "Petrol",
    "Food",
    "Subscription",
    "Social",
    "Phone",
    "Travel",
    "Payments",
    "Spiritual",
    "Learning",
    "Book",
    "Website",
    "Vehicle",
    "Business",
    "Trading",
    "Entertainment",
]